[package]
name = "card_game_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4"
dioxus-desktop = "0.4"
serde = "1.0.152"
# serde-xml-rs = "0.6.0"
# strong-xml = "0.6.3"
hard-xml = "1.21.0"
rand = { version = "0.8.5" }
toml = "0.7.1"

[profile.release]
opt-level = 3
